// import i18next from 'i18next';

i18next.init({
  lng: 'en',
  debug: true,
  resources: {
    en: {
      translation: {
        "language": "Language",
        "purePeace": "Pure Peace. Pure Life.",
        "bigHeader": "WORLD WIDE MEDITATION</br>FOR THE BENEFIT OF THE PLANET",
        "smallHeader": "Global prayer-meditation to harmonize the world",
        "invitation": "Dear friends, We invite you for global meditation April 4th 2020.",
        "p1": "The power of radical changes is within us. It can be multiplied many times if realized in sync collectively. </br>Together we may start the creation of the new world. The world of the Golden Age ruled by Love Freedom, Abundance, Peace, and Perfect Health.</br></br> What is the most powerful instrument we have for liberation, resetting, and healing humanity and life on this planet? It’s directed group intention through mass meditation. </br></br>Let’s use it to the full extent!",
        "p2": "</br></br>We believe that pandemics, wars, social tensions, and climate change all give us an opportunity to change for the best the rise of Consciousness on this planet. </br>We may voluntarily use the power given by the Creator - the power of our consciousness - and take responsibility for what’s happening. Say no to a destructive way of life, stop destroying ourselves and the planet, use the willpower to influence the course of events healing the world for the benefit of all living. </br></br>This is possible by consolidating the willpower of many people in a single thrust, concentration on the positive, and emotions in the process of prayer-meditation that allow the creation of a matrix of new and clean and harmonic world. </br>Whatever your personal views and beliefs might be on the subject of Consciousness on the planet we all see the necessity to choose a more ecological model of population behavior with respect to ourselves and the planet as a whole.</br></br>Together we can do a lot!",
        "p3": "Let’s gather together for a global meditation april 4th and unite as many places on earth as possible in a state of joy, love, and thankfulness. Let these islands and continents become anchors for energies of Peace, Harmony, Abundance, Freedom and Healing!</br>We must use the power of our collective mind and intention to form a powerful transformational wave particularly on key dates.We will focus solely on the final goal - harmonizing life on the planet and forming the mind of a New Man.</br></br>We ask you to widen this power by asking everyone who looks at your social network pages, reads your books and blogs. Spread the word that mass meditations on a global scale may become an effective instrument of transformation and a main priority in this situation the world found itself in. </br></br>Let’s begin with a powerful astrological portal that opens April 4th 2020 and do this regardless of time of the day it fits in your local time. It’s only 20 minutes that can change the fate of our planet. </br>Together we will create a miracle by joining as a single Consciousness and a single Heart in the exact moment Jupiter and Pluto come together. That is April 4th 22:45 EST. We will anchor these high vibrational energies and channel them with the help of our intention to free and heal humanity!</br></br>Have you ever felt a powerful surge of love and calm in the presence of a spiritually powerful person which is pleasant and easy to be in? So why don’t we develop this wonderful ability to change the world for the best with the help of love and awaken what is called Soul in people?</br></br>",
        "important": "IMPORTANT!",        
        "p4": "</br>During meditation it is necessary to feel peace within ourselves and not just think of the need to heal the mind and planet. Forming intentions we must imagine the changes and feel like these changes have already happened. We must see images of harmony, clean and peaceful planed and happy people, feel the smell of flowers, hear the sound of waves and the whisper of leaves, see ourselves in these beautiful places and live through this experience vividly. It’s very important to convince ourselves that this world is the reality, that it’s happening  and citizens of the world are ready to accept this new reality.</br></br></br>",
        "meditationTechnique": "Meditation technique.",
        "p5": "</br>1. Use any familiar and available technique to enter relaxed calm and well meaning state of mind.</br></br>2. Express your intention to use this prayer-meditation as an instrument to harmonize your state, improving the quality of life for all beings on the planet, to clean and renew the natural potential of this planet.</br></br>3.Sit in a comfortable pose and close your eyes lifting the gaze up 20 degrees over the horizon without lifting your face. Having done a couple inhale-exhales shift your attention to the powers of a subtle world that are important to you inviting them to take part and assist in prayer-meditation. </br></br>Imagine a bright white pillar of light shining from above Universal Consciousness  bringing the love of Creator and the power to change upon us. This bright light goes through your head and further through the body to the center of Earth.</br>Imagine a ball of golden light being born in the center of Earth. Imagine it’s light brightening and the ball becoming too bright to look upon. Imagine a powerful beam of golden light carrying Power and maternal love of the planet to its children.</br></br>Two beams of light meet inside your body and a clot of bright warm healing light of love appears in that place. It’s intensity rises and a warm healing light of love and potential spreads to every cell of your body enriching it with energy and power of change.</br></br>",
        "p6": "You feel the surge of power, light, and energy within. Imagine this inner light becoming brighter and your body glowing with beautiful golden-white light of the power of Spirit. You start emitting thousands of little golden beams spreading to all living beings on this planet and filling them with this new healing energy of love and compassion. And the Light spreads across the planet filling the hearts and minds of people and presenting them with understanding and power of joyful transformation of the world. This light cleans the seas, rivers, springs and air in the cities. Gone are the problems and illnesses. Happy voices of animals, birds, and children are heard throughout the planet.</br></br>The light transforms the fears, aggression, lies, and disharmony of this world in the hearts and minds of people. At the same time it softly wraps people and enriches them with the new consciousness, more compassionate and happier than before. It brings more love, light and harmony to the all living creatures on the planet and the mother-Earth herself.</br>At the same time you’re growing in size and the body of light grows proportionally taking up more and more space. The power of happy healing love grows proportionally. And here it is in front of you - small blue ball - it’s our dear and beloved planet, our home. You feel the same tender love and wrap it with a golden cloud of light. You know that at this moment all living beings and the planet itself respond to your love and care. At the same time the process of cleaning and healing goes ever more intensely.</br></br>Remain in this state of unity with Earth and its inhabitants for as long as you feel like and then come back in your body.</br></br>Take notice which part of your body holds this source of golden spiritual light. Put your hand on this place and remember your feelings. Next time you put your hand on this place, close your eyes and lift your gaze you’ll be able to enter much faster and easier this beautiful resourceful place of inner enlightenment.</br></br></br>",
        "timeOfEvent": "TIME OF EVENT.",
        "p7": "</br>Mass meditation is being held April 4th 2020 at 22:45 EST exactly in New York, (April 5gh 2020 at 05:45 MCK in Moscow) for 20 minutes.</br></br>This corresponds to 21:45CDT in Chicago, 20:45 MDT in Denver and 19:45 PDT in Los-Angeles - April 4th. Europe and Asia will already be on April 5gh and the moment of activation which will happen 03:45 BST in London, 04:45 CEST in Paris, 04:45 EET in Cairo, 05:45 MCK in Moscow, 10:45 CST in Taipei and Beijing, 11:45 JST in Tokyo and 12:45 AEST in Sydney.</br></br>",
        "p8": "You can check the time of meditation for you locale here:",
        "p9": "2020 is a powerful astrological year which takes us into the long awaited aquarius era. Astrologists around the world predicted that 2020 will become a “determining year for the fate of humanity”, “turning point”, and “serious redistribution of power”. Much of this is related to the unprecedented astrological alignment including exceptionally powerful joining Jupiter/Pluto starting april 4th and a subsequent triple joining Saturn-Pluto-Jupiter which last happened 700 years ago.",
        "peacefulExperiment": "PEACEFUL EXPERIMENT.",
        "p10": "</br>A group of researchers conducted an experiment during the Lebanon-Israel war that started in 1982. A group of people were trained to feel peace inside without thoughts of peace or prayer for peace but with convincing themselves that this peace already exists in them.</br></br>Participants practiced meditation with a goal of obtaining described feelings. Those people were thrown into war-torn regions of the Middle East at specially designated time on specially chosen days of the month. And when they glow with the sense of peace in the middle of all this horror, acts of terror stopped, war crimes dropped, number of injured taken to hospitals and number of road accidents declined.</br></br>Such studies confirm discoveries made earlier: even when a small percentage of the population acquires a state of inner peace and calm that state is reflected in the surrounding world. This study was named “International project for peace in the Middle East”. Results were published in “Journal of conflict resolution” (1988).</br>",
      }
    },
    ru: {
      translation: {
        "language": "Язык",
        "purePeace": "Чистый Мир. Чистая Жизнь.",
        "bigHeader": "ВСЕМИРНАЯ МЕДИТАЦИЯ</br>ВО БЛАГО ПЛАНЕТЫ",
        "smallHeader": "Международная молитва-медитация для гармонизации процессов в мире.",
        "invitation": "Друзья, приглашаем вас на международную молитву-медитацию 4 апреля 2020г в 22:45 EST</br>(5 апреля в 05:45 Москва).",
        "p1": "Сила для радикальных изменений находится внутри нас, и она может усилиться многократно, если будет реализована в унисон коллективно.    </br>Вместе мы можем приступить к созданию нового мира — мира Золотого Века, где царят Любовь, Свобода, Изобилие, Мир и Совершенное Здоровье!</br></br>НАИБОЛЕЕ МОЩНЫЙ ИНСТРУМЕНТ, КОТОРЫЙ МЫ ИМЕЕМ ДЛЯ ОСВОБОЖДЕНИЯ, ОБНОВЛЕНИЯ И ИСЦЕЛЕНИЯ ЧЕЛОВЕЧЕСТВА И ВСЕЙ ЖИЗНИ НА ЭТОЙ ПЛАНЕТЕ — НАПРАВЛЕННОЕ ГРУППОВОЕ НАМЕРЕНИЕ ЧЕРЕЗ МАССОВУЮ МЕДИТАЦИЮ. </br></br>Давайте использовать его в полной мере!",
        "p2": "</br></br>Мы считаем, что происходящие сейчас на земле- эпидемии, войны, рост социального напряжения, изменение климата и природные катаклизмы являются знаковыми и дают шанс изменить к лучшему тенденции развития Разума на планете.</br>Мы можем добровольно использовать силу, дарованную Создателем - силу своего разума и взять ответственность за происходящее на себя. Отказаться от деструктивного образа мысли и поведения, перестать разрушать себя и планету и волею своей повлиять на развитие событий, исцеляя мир во благо всех живущих.</br></br>Это возможно за счёт консолидации воли множества людей в едином порыве, концентрации на позитивных образах и эмоциях в процессе молитвы-медитации, что позволит создать матрицу нового чистого и гармоничного мира.</br>Какими бы ни были ваши личные взгляды или убеждения в отношении эволюции Разума на планете, мы все видим необходимость выбора более экологичной модели поведения популяции по отношению к себе и к планете в целом.</br></br>Вместе мы можем многое!",
        "p3": "</br></br>Давайте соберемся вместе для глобальной медитации 4 апреля и в состоянии радости, любви и благодарности объединимся как множество точек Света. И пусть эти острова и материки Света станут якорями энергий Мира, Гармонии, Изобилия, Свободы и Исцеления!</br>Мы должны использовать силу нашего коллективного разума и намерения для формирования мощной трансформационной волны преображения особенно в ключевые даты. Мы сосредоточимся исключительно на конечной цели — гармонизации жизни на планете и формировании сознания Новый Человек.</br></br>Мы просим вас расширить эту силу, обратившись ко всем, кто следит за вашими страницами в социальных сетях, читает ваши книги или блоги и сообщить, что массовые медитации в глобальном масштабе могут стать эффективным инструментом преображения и главным приоритетом в создавшейся ситуации в мире.</br></br>Давайте начнём с мощного астрологического портала, который откроется 4 апреля 2020 и сделаем это независимо от того, в какое время суток он попадает в ваш часовой пояс. Это всего лишь 20 минут, которые могут изменить всю судьбу нашей планеты!</br>Вместе мы создадим чудо, объединившись как единый Разум и единое Сердце в точный момент соединения Юпитера и Плутона, то есть 4 апреля в 22:45 EST (5 апреля в 05:45 Москва), чтобы заякорить эти высокие вибрационные энергии и направить их с помощью нашего намерения на освобождение и исцеление человечества!</br></br>Скажите, вы чувствовали в присутствие духовно сильной личности силовое поле любви и спокойствия, находиться в котором приятно и легко? Так почему бы нам с вами не развивать в себе эту чудодейственную способность с помощью любви менять мир к лучшему, пробуждая в людях то, что называется Душой?</br></br>",
        "important": "ВАЖНО!",
        "p4": "</br>Во время медитации необходимо ощущать мир внутри себя, не просто мыслить о необходимости исцеления разума и планеты, формулируя пожелания, а живо представлять происходящие изменения и чувствовать себя так, как будто эти изменения уже произошли. Видеть гармоничные образы чистой, мирной планеты и радостных людей, чувствовать ароматы цветов, слышать шум прибоя и шелест листвы, видеть себя в в этих прекрасных местах и эмоционально, ярко переживать этот чудесный опыт. Очень важно убедить себя, что этот мир – реальность, что он уже проявляется, что жители земли готовы принять новую реальность.</br></br></br>",
        "meditationTechnique": "ТЕХНИКА ПРОВЕДЕНИЯ МЕДИТАЦИИ.",
        "p5": "</br>1. Используйте любую знакомую и доступную вам технику войдите в расслабленное, спокойное и доброжелательное состояние сознания.</br></br>2. Выразите своё намерение использовать эту молитву-медитацию в качестве инструмента для гармонизации своего состояния, улучшения качества жизни всех живущих на планете существ, очищения и обновления природного потенциала планеты.</br></br>3. Сядьте в удобном месте в удобную позу и закройте глаза, подняв взгляд на 20 градусов над линией горизонта (не поднимая при этом лица) . Сделав два спокойных вдоха-выдоха, обратитесь к значимым для вас силам тонкого мира и пригласите участвовать и оказать необходимое содействие в молитве-медитации.</br></br>Представьте столб сияющего белого света Космического Разума, излучаемый сверху и несущий любовь Создателя и потенциал преображения. Этот сияющий свет проходит через вашу голову и далее через тело в центр Земли.</br>В центре Земли зарождается шар золотого света, его свечение нарастает, шар становится ослепительно-ярким и от него к поверхности земли устремляется мощный золотой луч, несущий Силу и материнскую любовь планеты к своим детям.</br></br>Два луча встречаются в вашем теле и в месте встречи возникает сгусток яркого тёплого бело-золотистого света. Свечение его нарастает и тёплый исцеляющий свет любви и потенциалов распространяется в каждую клеточку вашего тела, насыщая энергией и силой преображения.</br></br>",
        "p6": "Вы чувствуете наполнение силой , светом и энергией изнутри. Представьте, что это внутреннее свечение становится все ярче и вот уже ваше тело светится прекрасным бело-золотым светом силы Духа и вы начинаете излучать тысячи золотых лучиков, тянущихся ко всем живым существам планеты, наполняя их новой целительной энергией любви и сострадания. И Свет распространяется по планете, наполняя умы и сердца людей, даря понимание и силу радостного преображения мира. Этот свет очищает моря, реки, источники и воздух в городах, уходят проблемы и болезни, и по планете звучат радостные голоса зверей и птиц, звонкий смех детей.</br></br>Свет преображает все страхи, всю агрессию, всю ложь и дисгармонию этого мира в умах и сердцах людей.Мягко по-матерински он укутывает людей и наделяет новым сознанием, более сострадательным, более радостным, несущим больше любви, света и гармонии живущим на планете существам и самой матушке Земле.</br>Вы при этом растете, увеличиваясь в размере, и сообразно увеличивается ваше тело света, занимая всё больше и больше пространства. Вместе с этим растёт и транслируемая вами сила радостной, исцеляющей любви. И вот уже перед вами маленький голубой шар, это наша родная любимая планета-наш дом. Вы испытываете к ней чувство нежной любви, и укутываете ее золотым облаком света, и знаете, что в этот момент вам радостно отвечают на вашу любовь и заботу все существа земли и сама мать планета. При этом на ней интенсивно происходят процессы очищения и исцеления.</br></br>Побудьте в этом состоянии связи-единения с Землёй и ее обитателями столько, сколько почувствуете нужным и затем возвращайтесь в тело.</br></br>Заметьте, в какой части тела находится источник этого золотого духовного света. Положите руку на это место и запомните те чувства, которые сейчас наполняют вас. В следующий раз положив руку на это место, закрыв глаза и подняв взгляд вы уже быстрее и легче сможете войти в это прекрасное ресурсное состояние внутренней светимости.</br></br></br>",
        "timeOfEvent": "ВРЕМЯ ПРОВЕДЕНИЯ.",
        "p7": "</br>Массовая медитация проводится 4 апреля 2020 года ровно в 22:45 EST в Нью-Йорке, (5 апреля 2020 в 05:45 МСК в Москве) в течение 20 минут.</br></br>Это равно 21:45 CDT в Чикаго, 20:45 MDT в Денвере и 19:45 PDT в Лос-Анджелесе — 4 апреля. Европа и Азия уже будут иметь 5 апреля в момент активации, которая будет 03,45 BST в Лондоне, 04:45 CEST в Париже, 04:45 EET в Каире, 05:45 МСК в Москве, 10:45 CST в Тайбэе и Пекине, 11:45 JST в Токио и 12:45 AEST в Сиднее.</br></br>",
        "p8": "Вы можете проверить время медитации для вашего часового пояса здесь:",
        "p9": "2020 год — это мощный астрологический год, который приведёт нас в долгожданную Эру Водолея. Астрологи всего мира предсказали, что 2020 год станет «определяющим годом судьбы человечества», «переломным моментом» и «серьёзным перераспределением власти».Во многом это связано с беспрецедентным астрологическим выравниванием, включая чрезвычайно мощное соединение Юпитер / Плутон, начинающееся 4 апреля, и последующее тройное соединение Сатурн-Плутон-Юпитер, которое в последний раз произошло 700 лет назад.",
        "peacefulExperiment": "МИРНЫЙ ЭКСПЕРИМЕНТ.",
        "p10": "</br>Во время ливано-израильской войны, начавшейся в 1982 году, ряд исследователей провёл эксперимент, в ходе которого группу людей обучали способности ощущать мир внутри себя, но не с помощью мыслей о мире или молитвы «во благо» мира, а с помощью убеждения в том, что он, этот мир, в них уже присутствует.</br></br>В ходе эксперимента его участники с целью обретения указанного чувства прибегали к медитации.В специально назначенное время в специально выбранные дни месяца этих людей забрасывали в истерзанные войной регионы Ближнего Востока. И когда они посреди всего этого кошмара преисполнялись чувством мира, террористические действия прекращались, преступления против мирных жителей шли на спад, количество пострадавших, доставляемых в госпитали, и число дорожных происшествий уменьшалось.</br></br>Такие исследования подтвердили ранее сделанные открытия: когда даже небольшой процент населения обретает внутреннее состояние мира и покоя, это состояние отражается в окружающем мире.Это исследование получило название «Международного проекта мира на Ближнем Востоке», а его результаты опубликовал «Журнал разрешения конфликтов» (1988 г.).</br>",
      }
    }
  }
}, function(err, t) {
  // init set content
  updateContent();
});

function updateContent() {
  document.getElementById('languageSelector').innerHTML = i18next.t('language');
  document.getElementById('purePeace').innerHTML = i18next.t('purePeace');
  document.getElementById('bigHeader').innerHTML = i18next.t('bigHeader');  
  document.getElementById('smallHeader').innerHTML = i18next.t('smallHeader');
  document.getElementById('invitation').innerHTML = i18next.t('invitation');  
  document.getElementById('p1').innerHTML = i18next.t('p1');    
  document.getElementById('p2').innerHTML = i18next.t('p2');      
  document.getElementById('p3').innerHTML = i18next.t('p3');        
  document.getElementById('important').innerHTML = i18next.t('important');        
  document.getElementById('p4').innerHTML = i18next.t('p4');
  document.getElementById('meditationTechnique').innerHTML = i18next.t('meditationTechnique');
  document.getElementById('p5').innerHTML = i18next.t('p5');  
  document.getElementById('p6').innerHTML = i18next.t('p6');
  document.getElementById('timeOfEvent').innerHTML = i18next.t('timeOfEvent');
  document.getElementById('p7').innerHTML = i18next.t('p7');
  document.getElementById('p8').innerHTML = i18next.t('p8');
  document.getElementById('p9').innerHTML = i18next.t('p9');    
  document.getElementById('peacefulExperiment').innerHTML = i18next.t('peacefulExperiment');
  document.getElementById('p10').innerHTML = i18next.t('p10');  
}

function changeLng(lng) {
  i18next.changeLanguage(lng);
}

i18next.on('languageChanged', () => {
  updateContent();
});